# Generated by Django 6.0.3 on 2026-03-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_expense_date_alter_timetable_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='time',
        ),
        migrations.AddField(
            model_name='timetable',
            name='period1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='timetable',
            name='period2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='timetable',
            name='period3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='timetable',
            name='period4',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='timetable',
            name='period5',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='timetable',
            name='period6',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='timetable',
            name='period7',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
