# Generated by Django 6.0.3 on 2026-03-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_timetable_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='p1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='p2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='p3',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='p4',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='p5',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='p6',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='p7',
            field=models.CharField(max_length=50),
        ),
    ]
