# Generated by Django 6.0.3 on 2026-03-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_note_video_link_alter_timetable_p1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='notes/'),
        ),
    ]
