# Generated by Django 6.0.3 on 2026-04-12 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_note_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='p1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='p2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='p3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='p4',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='p5',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='p6',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='p7',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='submissions/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.assignment')),
            ],
        ),
    ]
