# Generated by Django 6.0.3 on 2026-04-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_timetable_p1_alter_timetable_p2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='item',
        ),
        migrations.AddField(
            model_name='expense',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
