# Generated by Django 6.0.3 on 2026-04-17 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_calendarevent_student_alter_assignment_title_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalendarEvent',
        ),
    ]
