# Generated by Django 6.0.3 on 2026-04-17 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_delete_calendarevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
